### ISSUE TITLE
大牛，你这插件要怎么使用呢？

### ISSUE THREAD

**Issue by suzi404** [jinzhe/vue-calendar#13]
`import VueCalendar from 'vue-calendar'
Vue.use(VueCalendar);
`
这样把插件引用进来会报错，还有你的demo里面按组件的方式引入在vue2.0会不兼容，求大神指点
`export default {
    components:{
        calendar
    },`

**Comment by jinzhe** [comment]
这个只支持vuejs 1.x，还没有兼容到2.0
