### ISSUE TITLE
本地如何重现？

### ISSUE THREAD

**Issue by byr-gdp** [jinzhe/vue-calendar#2]
<del>我想在本地重现 gif 效果，但始终跑不起来。希望能给予指导或更详细的 demo</del>

本地可以预览了，但出现样式问题。

**Comment by jinzhe** [comment]
样式问题我没有考虑，这个组件是我的项目中剥离出来的。做个小调整应该可以用的。

**Comment by byr-gdp** [comment]
@jinzhe 对。我在你项目基础上改了下，将 demo.vue 和 calendar.vue 合成一个文件，只需 require 组件即可。但暂时觉得 require(.vue) 不够优雅，如果能直接 .use 就好了。

**Comment by jinzhe** [comment]
因为有css 和html，做成插件好像不太合适

**Comment by byr-gdp** [comment]
@jinzhe ok，有空在研究研究。
