### ISSUE TITLE
运行不起来~！

### ISSUE THREAD

**Issue by zwzhong00** [jinzhe/vue-calendar#22]
我是直接clone https://github.com/jinzhe/vue-calendar.git
然后npm install 再 npm run dev
莫名奇妙的报一大堆错

**Comment by mote-ice** [comment]
我也运行不起来

**Comment by xiaopig123456** [comment]
我也运行不起来！

**Comment by Lee66** [comment]
一样啊，不知道为什么

**Comment by jinzhe** [comment]
这个是vuejs1.x
