### ISSUE TITLE
上月的最后一天计算有误？

### ISSUE THREAD

**Issue by byr-gdp** [jinzhe/vue-calendar#3]
`calendar.vue` Line 84:

> lastDayOfLastMonth = m == 0 ? new Date(y - 1, 11, 0).getDate() : new Date(y, m, 0).getDate();//最后一月的最后一天

实际上这样就可以了

> var lastDayOfLastMonth = new Date(y, m, 0).getDate();

**Comment by jinzhe** [comment]
已更正
