### ISSUE TITLE
请问大大，支持2.0吗？

### ISSUE THREAD

**Issue by amourz** [jinzhe/vue-calendar#30]

**Comment by jinzhe** [comment]
支持

**Comment by amourz** [comment]
恩恩，已经集成进自己的项目了，2.0可用。提个建议，现在每次点击日历控件进去，必定有一个返回值。有时候我们的需求是日期并不是必填项，能不能加个“取消”按钮，点击此按钮则返回空值。

**Comment by jinzhe** [comment]
这个你可以自己在调用的vue文件控制，select的时候先不要关闭隐藏界面或者赋值，可以放到其他变量。然后自己做个提交或者取消按钮去控制即可。

**Comment by amourz** [comment]
谢谢，已加上
