### ISSUE TITLE
你好，麻烦问下   display 如何动态的设置时间

### ISSUE THREAD

**Issue by vincent-cong** [jinzhe/vue-calendar#35]
display 如何动态的设置时间

**Comment by wjz473** [comment]
calendar.vue中，修改watch，添加对value的监听（this.init()不知道有什么影响）

watch:{
        events(){
            this.render(this.year,this.month)
        },
        value:function(){
        	this.init();
        }
    },

**Comment by jinzhe** [comment]
已增加
