### ISSUE TITLE
BUG:获取events的时候,月份和日期没有补零,导致无法读取日期数据

### ISSUE THREAD

**Issue by ironmancaijian** [jinzhe/vue-calendar#41]
// 获取自定义事件
        getEvents(y,m,d){
            if(d<10){d = '0'+d}
            if(m<10){m = '0'+m}
            if(Object.keys(this.events).length==0)return false;
            if(this.events[y+"-"+m+"-"+d]!=undefined){
                
                return {
                    eventName:this.events[y+"-"+m+"-"+d]
                }
            }
            return {}
        },

**Comment by jinzhe** [comment]
这个是一个约定，设置的事件日期不能加0的，你要代入参数的时候去掉0。

**Comment by wxy666** [comment]
现在可以了吗 博主
