### ISSUE TITLE
支持禁止点击日历选择，默认展示给定选中的日期吗？

### ISSUE THREAD

**Issue by lsqswl** [jinzhe/vue-calendar#44]
如题

**Comment by lsqswl** [comment]
例子中的calendar5 如果设置默认日期，如下，指定的是11月，实际上选中的是12月。 

value:[[2017,11,1],[2017,11,3]], //默认日期

**Comment by lsqswl** [comment]
希望大佬小改一下，并且增加一个禁止用户点击日期的开关。 我这边现在急用先自行处理了。

**Comment by lsqswl** [comment]
bug:
value:[[2017,11,1]],//默认日期 calendar5 中，如果默认日期是这个，会导致2017年的2月11号被选中。

bug是因为这个判定引起的。
if( this.value.filter(v => v.join("") == [this.year,this.month,i].join("")).length>0 ){
2017.1.11 与 2017.11.1 在这个if里是相等的。
由于multi类型的，月份会被多加1。所以现象就是2017.12.1 与 2017.2.11点击任意一个都是同时选中。2017.12.2与2017.2.12点击任意一个都是同时选中。等等。。。。。

**Comment by lsqswl** [comment]
总结一下问题：
1. 多选calendar5, 选择2017年12月的前几个日期，2017年2月份的日期会跟着被选中。
2.多选calendar5, 设置value:[[2017,11,1],[2017,11,3]], //默认日期，明明设置的是11月，选中的却是12月。
希望新增一个功能：
3.可以控制日历日期不让用户选中。即select方法直接return。

**Comment by lsqswl** [comment]
[calendar.vue.zip](https://github.com/jinzhe/vue-calendar/files/1524618/calendar.vue.zip)

三点都修改完毕。

**Comment by jinzhe** [comment]
已经加上了屏蔽日期和修复了多选的bug
