### ISSUE TITLE
多选农历 在月末 和月初 日期返回好像有点小问题

### ISSUE THREAD

**Issue by dongwenxu** [jinzhe/vue-calendar#45]
![f ey hsarw24m je mpi](https://user-images.githubusercontent.com/22827993/33657795-55b9f5ae-dab5-11e7-910f-b8c69308a830.png)
![t_o2o0tovhkbe 9gbb emu](https://user-images.githubusercontent.com/22827993/33657800-59672ffa-dab5-11e7-8f2a-ed2976348c2f.png)

**Comment by lsqswl** [comment]
https://github.com/jinzhe/vue-calendar/issues/44

**Comment by lsqswl** [comment]
你这问题跟我提的那是一样的吧。作者说已修复，我还没验证，我那问题里有修复的代码。

**Comment by jinzhe** [comment]
http://jinzhe.github.io/vue-calendar/
看看demo，我验证了下没有问题

**Comment by dongwenxu** [comment]
第二个多选 农历 的例子 你测试下 是有问题的      单选英文的没问题

**Comment by lsqswl** [comment]
@dongwenxu dongwenxu 你的代码是旧的吧。

**Comment by dongwenxu** [comment]
![1](https://user-images.githubusercontent.com/22827993/33749679-0124728e-dc0a-11e7-80bc-d8b7959c14b1.png)

**Comment by lsqswl** [comment]
我试了没问题。代码我上次已经传上来了。看二楼回复。
