### ISSUE TITLE
选择年份或者月份箭头左右点击的时候，希望能抛出方法来。

### ISSUE THREAD

**Issue by lsqswl** [jinzhe/vue-calendar#46]
我想切换月份或者年份时，请求对应月份的数据。

**Comment by lsqswl** [comment]
我先自己实现了，望大佬增强一下功能哈。

**Comment by lsqswl** [comment]
@next="next" @prev="prev" @selectYear="selectYear"

        selectYear(value){
            this.yearsShow=false
            this.year=value
            this.render(this.year,this.month);
            this.$emit('selectYear',this.year,this.month+1);
        },

        prev(e) {
            e.stopPropagation()
            if (this.month == 0) {
                this.month = 11
                this.year = parseInt(this.year) - 1
            } else {
                this.month = parseInt(this.month) - 1
            }
            this.render(this.year, this.month)
            this.$emit('prev',this.year,this.month+1)
        },
        //  下月
        next(e) {
            e.stopPropagation()
            if (this.month == 11) {
                this.month = 0
                this.year = parseInt(this.year) + 1
            } else {
                this.month = parseInt(this.month) + 1
            }
            this.render(this.year, this.month)
            this.$emit('next',this.year,this.month+1)
        },

**Comment by lsqswl** [comment]
总结一下：就是帮加上以下三句话：
this.$emit('prev',this.year,this.month+1)
this.$emit('next',this.year,this.month+1)
this.$emit('selectYear',this.year,this.month+1);

**Comment by lsqswl** [comment]
我这个有问题，往前翻往后翻，赋值会出现错乱。我再想想看。往前翻赋值一个12.6 往后翻赋值一个12.5，结果可能会没显示或者错乱了。不知道问题出在哪。

**Comment by lsqswl** [comment]
,
        value() {
          this.render(this.year,this.month)
        }


watch那边加上对value的观察就完美了。模仿了一下异步更新event那个。原来是数据赋值太慢导致的。加个观察就好了。我顺便把emit放在render前面了。 总之搞定了。

**Comment by jinzhe** [comment]
加上了
