### ISSUE TITLE
请问大神，选择日期范围的时候可不可以直接返回日期长度啊？

### ISSUE THREAD

**Issue by Momoko7** [jinzhe/vue-calendar#53]
先谢谢大神啦~ 组件功能很强大了，但是如果跨月的话，月份天数不一样，怎么返回我选择的日期的总天数啊？

**Comment by Momoko7** [comment]
可以获取啦~  
我的解决方案是将开始日期和结束日期转换为时间戳，然后相减算出天数。
感觉这个方法有点笨拙，不晓得有没有更好的解决方案啊，还望指点一二~

**Comment by jinzhe** [comment]
正确的！也只能这样做。
