### ISSUE TITLE
魅族手机上日期竟然不见了

### ISSUE THREAD

**Issue by ejwdhr** [jinzhe/vue-calendar#55]
![qq 20180308102305](https://user-images.githubusercontent.com/19422579/37129586-b58e46cc-22ba-11e8-8e04-a5e5be18b84c.jpg)

**Comment by ejwdhr** [comment]
发现在魅族上days数组为空原因不明

**Comment by jinzhe** [comment]
什么浏览器？系统版本？浏览器版本？

**Comment by jinzhe** [comment]
![wechatimg5](https://user-images.githubusercontent.com/4435082/37133135-5a6daaaa-22cc-11e8-86f3-dfc3d2702eec.jpeg)
我用的红米5 plus 正常

**Comment by ejwdhr** [comment]
我用手机浏览器访问您的预览地址是正常的，但是导入calendar.vue使用后，在魅族上就不显示了，华为上是好的，发现华为手机上days数组中有数据而魅族中此数组为空导致没有日期显示。

**Comment by jinzhe** [comment]
这个估计是和你的项目冲突了吧，或者有纰漏。review一下代码
