### ISSUE TITLE
组件咋用到  自己项目中 ...

### ISSUE THREAD

**Issue by Live-forever** [jinzhe/vue-calendar#57]
老铁们, 你们都是怎么用的 啊, 我是把calendar.js, 和calendar.vue copy 到项目里去了, 再把 calendar 引入到我要用的地方 然后 他就报template or render function not defined , 请问 我这样用 有毛病 吗 ? 在线等......

**Comment by jinzhe** [comment]
demo里面怎么用就怎么用

**Comment by narine0** [comment]
就是看不懂demo才问的。

**Comment by roberthuang123** [comment]
> 老铁们, 你们都是怎么用的 啊, 我是把calendar.js, 和calendar.vue copy 到项目里去了, 再把 calendar 引入到我要用的地方 然后 他就报template or render function not defined , 请问 我这样用 有毛病 吗 ? 在线等......

把calendar.vue写成index.vue可以解决这个问题
