### ISSUE TITLE
很坑啊！ 我选中的是二月的某一天 最后显示的是1月的某一天， 这怎么玩？

### ISSUE THREAD

**Issue by ShenAlfred** [jinzhe/vue-calendar#60]
总之会在我选中的某个月份相对减去1， 没法玩下去了

**Comment by jinzhe** [comment]
怎么调用的？发代码上来看看

**Comment by NBSeven** [comment]
range属性设为true，单击某个日子，显示的月份比实际的月份少1

**Comment by bo2337285** [comment]
calendar.vue
select函数中的this.rangeBegin和this.rangeEnd上来月份就少1了,然后在735行那没有做月份+1处理就输出了,后面的else反倒是做了+1处理
修复办法也很简单,直接在540行的else内换成以下代码
```
begin = this.rangeBegin.concat([])
begin[1]++
end = this.rangeEnd.concat([])
end[1]++
```
